Use the cloudfront fronted domain for smoke tests
alphagov/govuk-coronavirus-business-volunteer-form pull request #190
Opened 2020-04-03 14:40 UTC by richardTowers

2020-04-03 14:41 UTC, brucebolt approved these changes

2020-04-06 17:55 UTC, issyl0 requested changes
Otherwise we'll be testing the redirect to GOV.UK. ;-)

2020-04-06 17:55 UTC, issyl0 commented on concourse/pipeline.yml
> +          URL: 'https://coronavirus-business-volunteers.service.gov.uk/'
```suggestion
          URL: 'https://coronavirus-business-volunteers.service.gov.uk/medical-equipment'
```

2020-04-06 17:57 UTC, issyl0 commented on concourse/pipeline.yml
> +          URL: 'https://coronavirus-business-volunteers.service.gov.uk/'
The same needs to happen with the staging smoke tests. I'll raise another PR.

2020-04-06 18:05 UTC, issyl0 approved these changes

2020-04-06 18:05 UTC, merged